# Generated by Django 3.2.8 on 2021-10-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='donefield',
            new_name='done',
        ),
    ]
